name: flutter_advance_multi_moduler_advance_architecture
environment:
  sdk: ^3.12.1

workspace:
  - core/**
  - features/**

dev_dependencies:
  melos: ^8.3.0

melos:
  command:
    bootstrap:
      # Define common dependencies to be updated in all packages
      dependencies:
        meta: ^1.11.0

      # Define common dev_dependencies to be updated in all packages
      dev_dependencies:
        build_runner: ^2.4.8
        flutter_lints: ^6.0.0
