name: flutter_advance_multi_moduler_advance_architecture
environment:
  sdk: ^3.12.1

workspace:
  - core/**
  - features/**

dev_dependencies:
  melos: ^8.3.0

melos:
  command:
    bootstrap:
      dependencies:
        meta: ^1.11.0
      dev_dependencies:
        build_runner: ^2.4.8
        flutter_lints: ^6.0.0

  scripts:
    clean: melos clean
    cleanAndBootstrap: melos clean && melos bootstrap
    test:
      run: melos exec --concurrency=1 -- flutter test
    update: flutter pub outdated
    upgrade: flutter pub upgrade --major-versions